# Generated by Django 3.2.19 on 2023-05-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_journey_isactive_journey_number_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='role',
            field=models.CharField(default='Player', max_length=15),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='kills',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
