# Generated by Django 3.2.19 on 2023-05-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20230503_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='JourneyType',
            field=models.CharField(blank=True, default='Journey', max_length=50, null=True),
        ),
    ]
