# Generated by Django 3.2.19 on 2023-05-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_journey_journeytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='wasPlayed',
            field=models.BooleanField(default=True),
        ),
    ]
