# Generated by Django 4.1.3 on 2023-05-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_match_wasplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournament.player'),
        ),
    ]
