# Generated by Django 4.1.3 on 2023-05-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_match_second_alter_match_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='Round',
            field=models.IntegerField(default=1),
        ),
    ]
