# Generated by Django 4.1.3 on 2023-05-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_journey_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='journeyRound',
            field=models.IntegerField(default=1),
        ),
    ]
